### ISSUE TITLE
Config PhpManager, DbManager

### ISSUE THREAD

**Issue by terabytesoftw** [yiisoft/rbac#10]
### What steps will reproduce the problem?
Config authManager:

```
'authManager' => [
    '__class'   => \yii\rbac\PhpManager::class,
]
```
### Additional info

'Exception 'yii\di\exceptions\InvalidConfigException' with message 'Missing required parameter "dir" when instantiating "yii\rbac\PhpManager".' `

How to configure it so that rbac works correctly ?

thanks.

| Q                | A
| ---------------- | ---
| Yii version      | 3.0 ?
| PHP version      | 7.1.26
| Operating system | Centos 7

**Comment by samdark** [comment]
It doesn't work right now but it will be clear on how to configure it when I'll finish refactoring it.
