### ISSUE TITLE
Refactor `AssignmentsStorageInterface`

### ISSUE THREAD

**Issue by vjik** [yiisoft/rbac#103]
**updateAssignmentsForItemName()**

In fact, method `updateAssignmentsForItemName()` rename rule or permission name in assignments storage.

Suggest refactor this method:
`updateAssignmentsForItemName(string $name, Item $item)`
↓
`renameItem(string $oldName, string $newName)`

Tests are also needed. Now tests are pass if remove call of this method from `Manager`.

**Other**

`getAssignments()` → `getAll()` 

`getUserAssignmentByName()` → `get()` 
We can get assigment only by role or permission name. This name is shortly without loss of meaning: get assignment from storage.

`addAssignment(string $userId, Item $item)` → `add(string $userId, string $itemName)`
We not need instance of `Item` here, item name enough.

`assignmentExist()` → `existItemAssignments()`
`assignmentExist` is not unambiguously: for user or for RBAC item.

`removeAssignment(string $userId, Item $item)` → `remove(string $userId, string $itemName)`
We not need instance of `Item` here, item name enough.

`removeAllAssignments()`  → `removeUserAssignments()`
We remove only user assignments, not all.

`removeAssignmentsFromItem(tem $item)` → `removeItemAssignments(string $itemName)`
We not need instance of `Item` here, item name enough.

`clearAssignments()` → `clear()`
This name is shortly without loss of meaning: clear storage.

**Comment by samdark** [comment]
`updateAssignmentsForItemName()` does not rename itsem itself. It is updating item name for all assignments i.e. `changeItemName($oldName, $newName)` would fit more.

**Comment by samdark** [comment]
assignmentExist() → has()

**Comment by samdark** [comment]
The rest of renaming sounds great 👍

**Comment by vjik** [comment]
> assignmentExist() → has()

`assignmentExist()` accepty only item name parameter. Another methods `remove`, `add`, `get` accepts user ID and item name.

Suggest so: `assignmentExist()` → `hasItem()`

**Comment by samdark** [comment]
Yes, that's better name 👍
