### ISSUE TITLE
`Manager::getDefaultRoles()` should getting roles from the storage instead of create new role

### ISSUE THREAD

**Issue by vjik** [yiisoft/rbac#105]
https://github.com/yiisoft/rbac/blob/37a0fe51e37de5925154e32cd9c19a2ae0d294f0/src/Manager.php#L457-L468

Should we create new role If it don't exists in storage? Or throw exception (I like this variant)?

**Comment by samdark** [comment]
Why getting it from the storage? We already have names and these are set as "default".

**Comment by vjik** [comment]
> Why getting it from the storage? We already have names and these are set as "default".

In RBAC system rules, permissions and other roles can be assign to role.

"default role" - this is only name of role, but not full role data.

**Comment by samdark** [comment]
Fixed in #114
