### ISSUE TITLE
Refactor `Manager`

### ISSUE THREAD

**Issue by vjik** [yiisoft/rbac#106]
**Constructor**

w/o changes:

```
__construct(
	RolesStorageInterface $rolesStorage,
	AssignmentsStorageInterface $assignmentsStorage,
	RuleFactoryInterface $ruleFactory,
	bool $enableDirectPermissions = false
)
```

**Access check**

w/o changes:

`userHasPermission($userId, string $permissionName, array $parameters = [])`

**Work with children**

I assume that the users of the package will mainly work with the names of RBAC items, and not with instances.

`canAddChild(Item $parent, Item $child)` → `canAddChild(string $parentName, string $childName)`
`addChild(Item $parent, Item $child)` → `addChild(string $parentName, string $childName)`
`removeChild(Item $parent, Item $child)` → `removeChild(string $parentName, string $childName)`
`removeChildren(Item $parent)` → `removeChildren(string $parentName)`
`hasChild(Item $parent, Item $child)` → `hasChild(string $parentName, string $childName)`

**Assignment of roles and permissions**

I assume that the users of the package will mainly work with the names of RBAC items, and not with instances.
Also swap method arguments for consistent with `AssignmentsStorageInterface` (methods `addAssignment()` and `removeAssignment`).

`assign(Item $item, string $userId)` → `assign(string $userId, string $itemName)`
`revoke(Item $role, string $userId)` → `revoke(string $userId, string $itemName)`

w/o changes:

`revokeAll(string $userId)`

**Getting info**

Rename methods to more clearly names. 

`getRolesByUser(string $userId)` → `getRolesByUserId(string $userId)`
`getPermissionsByRole(string $roleName)` → `getPermissionsByRoleName(string $roleName)`
`getPermissionsByUser(string $userId)` → `getPermissionsByUserId(string $userId)`
`getUserIdsByRole(string $roleName)` → `getUserIdsByRoleName(string $roleName)`

w/o changes:

`getChildRoles(string $roleName)`

**Manage roles, permissions and rules**

I assume that the users of the package will mainly work with the names of RBAC items, and not with instances.

`removeRole(Role $role)` → `removeRole(string $roleName)`
`removePermission(Permission $permission)` → `removePermission(string $permissionName)`

w/o changes:

`addRole(Role $role)` 
`updateRole(string $name, Role $role)`
`addPermission(Permission $permission)`
`updatePermission(string $name, Permission $permission)`
`addRule(RuleInterface $rule)`
`updateRule(string $name, RuleInterface $rule)`
`removeRule(string $ruleName)`

**Default roles**

w/o changes

`setDefaultRoleNames($roleNames)`
`getDefaultRoleNames()`
`getDefaultRoles()`

**Guest role**

w/o changes

`setGuestRoleName(?string $name)`

**Comment by samdark** [comment]
- [x] Constructor
- [x] Access check
- [x] Work with children
- [ ] Assignment of roles and permissions
- [ ] Getting info
- [ ] Manage roles, permissions and rules
- [ ] Default roles
- [ ] Guest role

**Comment by samdark** [comment]
Done in #114
