### ISSUE TITLE
Make rbac not dependent on framework core pacakges

### ISSUE THREAD

**Issue by samdark** [yiisoft/rbac#11]
**What?**

rbac package should not depend on any other package except PSR interfaces such as PSR-3 for logging or PSR-15 for cache.

It may depend on https://github.com/yiisoft/cache and https://github.com/yiisoft/log for development via `require-dev` composer section for running tests and development.

**Why?**

The RBAC package is general enough not to require anything from the core framework. If we'll make it dependency-free it could be used as a library thus expanding its adoption.

**What do with DbManager?**

Try relying on PDO.

**Comment by machour** [comment]
to be noted: This package still requires yii-core for \yii\helpers\VarDumper and \yii\base\Component

**Comment by samdark** [comment]
Is there any need for \yii\base\Component?
