### ISSUE TITLE
Add support PHP enums for use as role/permission/rule name

### ISSUE THREAD

**Issue by vjik** [yiisoft/rbac#111]

**Comment by samdark** [comment]
What's missing now?

**Comment by vjik** [comment]
If in application for reference of permissions used enum, then check access will be so:

```php
$manager->userHasPermission($userId, Permission::add_post->name)
```

With support of enum it will be more convenient:

```php
$manager->userHasPermission($userId, Permission::add_post)
```

**Comment by samdark** [comment]
OK. Since that changes public API, I think we can do it before release.

**Comment by vjik** [comment]
These changes will entail a change in `Yiisoft\Access\AccessCheckerInterface`, and therefore a major release of Yii Access.

**Comment by samdark** [comment]
That's OK.

**Comment by samdark** [comment]
After doing draft implementation and internal team discussion we've decided not to impement it:

1. It hiders typing.
2. It doesn't add much to the syntax.
