### ISSUE TITLE
Implement at least one DB-based adapter before release

### ISSUE THREAD

**Issue by samdark** [yiisoft/rbac#112]
Since it may affect public API.

**Comment by samdark** [comment]
Initial implementation is done.

**Comment by vjik** [comment]
Need check performance of queries in [yiisoft/rbac-cycle-db](https://github.com/yiisoft/rbac-cycle-db)

**Comment by samdark** [comment]
@arogachev is on it.

**Comment by vjik** [comment]
Waiting https://github.com/yiisoft/rbac-cycle-db/issues/17
