### ISSUE TITLE
Move concrete storage implementations to dedicated packages

### ISSUE THREAD

**Issue by samdark** [yiisoft/rbac#12]
- [x] PHP storage to https://github.com/yiisoft/rbac-php
- [ ] DB storage to https://github.com/yiisoft/rbac-db

**Comment by samdark** [comment]
It depends on if DBAL will be used. If so then `db` is fine. If it will be PDO then yes, individual drivers are needed.

**Comment by romkatsu** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Move concrete RBAC storage implementations to dedicated packages](https://trello.com/c/gyFnNOJr/60-move-concrete-rbac-storage-implementations-to-dedicated-packages)

**Comment by samdark** [comment]
DB storage to follow later. Separation is done.
