### ISSUE TITLE
Sug.: Add due date

### ISSUE THREAD

**Issue by kambizzandi** [yiisoft/rbac#21]
Hi
I have a suggestion:
1/ Add field 'due_date' to the assignment for controlling expiring in assignment.
2/ Add field 'due_date' to the item_child too.
They help allow temporary permissions to users. For a demo, for example.
Thanks

**Comment by phena109** [comment]
I think we should evaluate if having this built-in provide more benefit (or confusion) compare to user implement themselves on-demand. It feels to me keeping it bare bone would confuse us less. In fact, (as of writing) the `Item` and `Manager` class implemented the `updatedAt` and `createdAt` bothered me a bit as I prefer a different naming convention, let alone I don't need them to start with. If I need them, I just extend the classes.

**Comment by samdark** [comment]
Yeah. I agree.
