### ISSUE TITLE
How to disable permission on role to specific user?

### ISSUE THREAD

**Issue by donnyatspe** [yiisoft/rbac#239]
I have role "ABC", and this role has permissions like "create", "view", "update", "delete". 

And this role we assign to user "User A", "User B" and "User C".

If I want add new permission "publish" for "User C" only. It will add new record on assigment table.
If I want disable "create" for "User A" only, and other users still has permission. It is possible without change existing role?

![image](https://github.com/yiisoft/rbac/assets/113414216/3f1d31d8-0f85-4cc3-a3f4-e322216835a7)

can we do like this?

**Comment by samdark** [comment]
No. It's not possible by design.
