### ISSUE TITLE
Permission/Role additional attributes vectoring

### ISSUE THREAD

**Issue by ptheofan** [yiisoft/rbac#24]
The `Permission` and `Role` classes should be able to support additional attributes. For the sake of consistency, I would suggest in one of the following approaches.
1. `function getAttributes(): array` that by default returns all the public attributes of the class (modify by extending the class)
1. **or** using `Arrayable` Interface (haven't checked but hopefully it exists in Yii3 as well?)

Original discussion reference [here](https://forum.yiiframework.com/t/improving-the-rbac-to-accommodate-a-wider-range-of-popular-use-cases/123539/9)

**Comment by samdark** [comment]
Adding `getAttributes(): array` to https://github.com/yiisoft/rbac/blob/master/src/Item.php sounds fine.

**Comment by samdark** [comment]
Done.
