### ISSUE TITLE
Add ability to check multiple roles or permissions in userHasPermission method.

### ISSUE THREAD

**Issue by sptik12** [yiisoft/rbac#268]
Currently to check user permissions for several roles we compelled to  do something like      

function canDoSomething(CurrentUser $currentUser) {
 return $currentUser->can(Role1)
            || $currentUser->can(Role2)
            || $currentUser->can(Role3);
}

It will be great of we'll have ability to write
function canDoSomething(CurrentUser $currentUser) {
 return $currentUser->can([Role1, Role2, Role3])
}

**Comment by vjik** [comment]
To check permission need to pass parameters. These parameters can be different to each of permission. 

I think in this case better create new permission, and add it to Role1, Role2 and Role3. And then check one permission: `$currentUser->can('MyNewPermission')`.

**Comment by samdark** [comment]
@sptik12 for your use-case it's better to do as @vjik suggested, i.e., having a dedicated permission for this action.
