### ISSUE TITLE
rbac\BaseManager methods visibility

### ISSUE THREAD

**Issue by dmeroff** [yiisoft/rbac#4]
Hello!

At the moment I'm working on rbac web-interface, and I've stumbled upon following problems:

1) I want to get all available roles and permissions and show them to user. The problem is that there is no method that can return me both permisions and roles in one array. Currently I can do this only by merging two arrays of roles and permissions:

``` php
array_merge(Yii::$app->authManager->getRoles(), Yii::$app->authManager->getPermissions());
```

I'm suggesting to make `rbac\BaseManager::getItems($type)` public and make its' argument optional, so we will be able to get all roles and permissions via `Yii::$app->authManager->getItems()`.

2) The similar problem is with `getItem` method. If I want to get either role or permission I need to do two method call:

``` php
// try to find out if there is either role or permission with given name
if ($auth->getRole('admin') !== null && $auth->getRole('admin') !== null) {
  echo 'There is neither role nor permission with name "admin"';
}
```

So I'm suggesting to make `rbac\BaseManager::getItem()` public.

**Comment by samdark** [comment]
Reviewed it and decided not to make it public. Permissions and roles should be assigned separately so there should be no need to get these all on one go. Calling two methods should be fine if there's still such a need.
