### ISSUE TITLE
Is it possible to attach multiple roles to a single permission?

### ISSUE THREAD

**Issue by sosojni** [yiisoft/rbac#5]
I have 2 roles (Admin, User) with 4 permissions (Edit, Edit Own, Lock, Lock Own). Edit Own and Lock Own permissions are for User role and Edit and Lock permissions are for Admin role.

LockOwn has IsOwner rule attached to it so Users are able to lock only their own items.
EditOwn has IsOwner rule attached to it so Users are able to edit their own items.

What i want for EditOwn permission is to check is item "locked". I planned to attach IsLocked rule to EditOwn permission but it turns out i can not (as told on forums and few other places) or i cant find a way to do it. 

I dealt with it in very "dirty" way by creating additional permission EditOwnIsLocked which has IsLocked rule attached to it. Permission chain goes: 
Edit (permission)->EditOwn (permission)+IsOwn(rule)->EditOwnIsLocked(permission)+IsLocked(rule)->User(role) and it's working fine, but i feel like there should be way to skip creating additional permission just to check for additional role. 
I could delete IsOwner and IsLocked rules and create IsOwnerAndNotLocked rule and combine codes from roles that now exist, but that would mean i have to retype part of code that checks if item is locked every time i need to check if something is locked in combination with something else (for example once i get to Delete action...i will have to create new permission and attach new role that will check for "lock" status and "delete" status.

Am i thinking about it all wrong? I learned about it in official guide: http://www.yiiframework.com/doc-2.0/guide-security-authorization.html but i could not find anything about combining rules and/or using 2 rules on one permission etc.
It's my first touch with RBAC system so i do not exclude that i got it all very much wrong.

**Comment by samdark** [comment]
Decided not to implement multiple rules support.
