### ISSUE TITLE
Get all users having a RBAC role assignment

### ISSUE THREAD

**Issue by Kolyunya** [yiisoft/rbac#6]
Current implementation of RBAC managers can find users having only direct assignment to a specific role.

If role `Foo` is a parent of role `Bar` and role `Foo` is assigned to some user then `getUserIdsByRole()` won't list that user as having role `Bar`.

I think we should implement a method which will find all users having all (even indirect) assignments to a specific role. This is a common scenario - to list all (I mean _really_ all) users by role.

Having such method will add completeness and consistency to the manager interface. Current method implementation is even misleading in some way.

**Comment by samdark** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [RBAC. Get all users having a role assignment.](https://trello.com/c/7SQVdN6t/30-rbac-get-all-users-having-a-role-assignment)

**Comment by yiiliveext** [comment]
For what purpose it will be used?

**Comment by samdark** [comment]
RBAC admin panels.
